import SwiftUI

extension ColorList {
    static let Colors2 = [
        ColorData("C9FFA2", "Reef"),
        ColorData("C9FFE5", "Aero Blue"),
        ColorData("CA3435", "Flush Mahogany"),
        ColorData("CABB48", "Turmeric"),
        ColorData("CADCD4", "Paris White"),
        ColorData("CAE00D", "Bitter Lemon"),
        ColorData("CAE6DA", "Skeptic"),
        ColorData("CB8FA9", "Viola"),
        ColorData("CBCAB6", "Foggy Gray"),
        ColorData("CBD3B0", "Green Mist"),
        ColorData("CBDBD6", "Nebula"),
        ColorData("CC3333", "Persian Red"),
        ColorData("CC5500", "Burnt Orange"),
        ColorData("CC7722", "Ochre"),
        ColorData("CC8899", "Puce"),
        ColorData("CCCAA8", "Thistle Green"),
        ColorData("CCCCFF", "Periwinkle"),
        ColorData("CCFF00", "Electric Lime"),
        ColorData("CD5700", "Tenn"),
        ColorData("CD5C5C", "Chestnut Rose"),
        ColorData("CD8429", "Brandy Punch"),
        ColorData("CDF4FF", "Onahau"),
        ColorData("CEB98F", "Sorrell Brown"),
        ColorData("CEBABA", "Cold Turkey"),
        ColorData("CEC291", "Yuma"),
        ColorData("CEC7A7", "Chino"),
        ColorData("CFA39D", "Eunry"),
        ColorData("CFB53B", "Old Gold"),
        ColorData("CFDCCF", "Tasman"),
        ColorData("CFE5D2", "Surf Crest"),
        ColorData("CFF9F3", "Humming Bird"),
        ColorData("CFFAF4", "Scandal"),
        ColorData("D05F04", "Red Stage"),
        ColorData("D06DA1", "Hopbush"),
        ColorData("D07D12", "Meteor"),
        ColorData("D0BEF8", "Perfume"),
        ColorData("D0C0E5", "Prelude"),
        ColorData("D0F0C0", "Tea Green"),
        ColorData("D18F1B", "Geebung"),
        ColorData("D1BEA8", "Vanilla"),
        ColorData("D1C6B4", "Soft Amber"),
        ColorData("D1D2CA", "Celeste"),
        ColorData("D1D2DD", "Mischka"),
        ColorData("D1E231", "Pear"),
        ColorData("D2691E", "Hot Cinnamon"),
        ColorData("D27D46", "Raw Sienna"),
        ColorData("D29EAA", "Careys Pink"),
        ColorData("D2B48C", "Tan"),
        ColorData("D2DA97", "Deco"),
        ColorData("D2F6DE", "Blue Romance"),
        ColorData("D2F8B0", "Gossip"),
        ColorData("D3CBBA", "Sisal"),
        ColorData("D3CDC5", "Swirl"),
        ColorData("D47494", "Charm"),
        ColorData("D4B6AF", "Clam Shell"),
        ColorData("D4BF8D", "Straw"),
        ColorData("D4C4A8", "Akaroa"),
        ColorData("D4CD16", "Bird Flower"),
        ColorData("D4D7D9", "Iron"),
        ColorData("D4DFE2", "Geyser"),
        ColorData("D4E2FC", "Hawkes Blue"),
        ColorData("D54600", "Grenadier"),
        ColorData("D591A4", "Can Can"),
        ColorData("D59A6F", "Whiskey"),
        ColorData("D5D195", "Winter Hazel"),
        ColorData("D5F6E3", "Granny Apple"),
        ColorData("D69188", "My Pink"),
        ColorData("D6C562", "Tacha"),
        ColorData("D6CEF6", "Moon Raker"),
        ColorData("D6D6D1", "Quill Gray"),
        ColorData("D6FFDB", "Snowy Mint"),
        ColorData("D7837F", "New York Pink"),
        ColorData("D7C498", "Pavlova"),
        ColorData("D7D0FF", "Fog"),
        ColorData("D84437", "Valencia"),
        ColorData("D87C63", "Japonica"),
        ColorData("D8BFD8", "Thistle"),
        ColorData("D8C2D5", "Maverick"),
        ColorData("D8FCFA", "Foam"),
        ColorData("D94972", "Cabaret"),
        ColorData("D99376", "Burning Sand"),
        ColorData("D9B99B", "Cameo"),
        ColorData("D9D6CF", "Timberwolf"),
        ColorData("D9DCC1", "Tana"),
        ColorData("D9E4F5", "Link Water"),
        ColorData("D9F7FF", "Mabel"),
        ColorData("DA3287", "Cerise"),
        ColorData("DA5B38", "Flame Pea"),
        ColorData("DA6304", "Bamboo"),
        ColorData("DA6A41", "Red Damask"),
        ColorData("DA70D6", "Orchid"),
        ColorData("DA8A67", "Copperfield"),
        ColorData("DAA520", "Golden Grass"),
        ColorData("DAECD6", "Zanah"),
        ColorData("DAF4F0", "Iceberg"),
        ColorData("DAFAFF", "Oyster Bay"),
        ColorData("DB5079", "Cranberry"),
        ColorData("DB9690", "Petite Orchid"),
        ColorData("DB995E", "Di Serria"),
        ColorData("DBDBDB", "Alto"),
        ColorData("DBFFF8", "Frosted Mint"),
        ColorData("DC143C", "Crimson"),
        ColorData("DC4333", "Punch"),
        ColorData("DCB20C", "Galliano"),
        ColorData("DCB4BC", "Blossom"),
        ColorData("DCD747", "Wattle"),
        ColorData("DCD9D2", "Westar"),
        ColorData("DCDDCC", "Moon Mist"),
        ColorData("DCEDB4", "Caper"),
        ColorData("DCF0EA", "Swans Down"),
        ColorData("DDD6D5", "Swiss Coffee"),
        ColorData("DDF9F1", "White Ice"),
        ColorData("DE3163", "Cerise Red"),
        ColorData("DE6360", "Roman"),
        ColorData("DEA681", "Tumbleweed"),
        ColorData("DEBA13", "Gold Tips"),
        ColorData("DEC196", "Brandy"),
        ColorData("DECBC6", "Wafer"),
        ColorData("DED4A4", "Sapling"),
        ColorData("DED717", "Barberry"),
        ColorData("DEE5C0", "Beryl Green"),
        ColorData("DEF5FF", "Pattens Blue"),
        ColorData("DF73FF", "Heliotrope"),
        ColorData("DFBE6F", "Apache"),
        ColorData("DFCD6F", "Chenin"),
        ColorData("DFCFDB", "Lola"),
        ColorData("DFECDA", "Willow Brook"),
        ColorData("DFFF00", "Chartreuse Yellow"),
        ColorData("E0B0FF", "Mauve"),
        ColorData("E0B646", "Anzac"),
        ColorData("E0B974", "Harvest Gold"),
        ColorData("E0C095", "Calico"),
        ColorData("E0FFFF", "Baby Blue"),
        ColorData("E16865", "Sunglo"),
        ColorData("E1BC64", "Equator"),
        ColorData("E1C0C8", "Pink Flare"),
        ColorData("E1E6D6", "Periglacial Blue"),
        ColorData("E1EAD4", "Kidnapper"),
        ColorData("E1F6E8", "Tara"),
        ColorData("E25465", "Mandy"),
        ColorData("E2725B", "Terracotta"),
        ColorData("E28913", "Golden Bell"),
        ColorData("E292C0", "Shocking"),
        ColorData("E29418", "Dixie"),
        ColorData("E29CD2", "Light Orchid"),
        ColorData("E2D8ED", "Snuff"),
        ColorData("E2EBED", "Mystic"),
        ColorData("E2F3EC", "Apple Green"),
        ColorData("E30B5C", "Razzmatazz"),
        ColorData("E32636", "Alizarin Crimson"),
        ColorData("E34234", "Cinnabar"),
        ColorData("E3BEBE", "Cavern Pink"),
        ColorData("E3F5E1", "Peppermint"),
        ColorData("E3F988", "Mindaro"),
        ColorData("E47698", "Deep Blush"),
        ColorData("E49B0F", "Gamboge"),
        ColorData("E4C2D5", "Melanie"),
        ColorData("E4CFDE", "Twilight"),
        ColorData("E4D1C0", "Bone"),
        ColorData("E4D422", "Sunflower"),
        ColorData("E4D5B7", "Grain Brown"),
        ColorData("E4D69B", "Zombie"),
        ColorData("E4F6E7", "Frostee"),
        ColorData("E4FFD1", "Snow Flurry"),
        ColorData("E52B50", "Amaranth"),
        ColorData("E5841B", "Zest"),
        ColorData("E5CCC9", "Dust Storm"),
        ColorData("E5D7BD", "Stark White"),
        ColorData("E5D8AF", "Hampton"),
        ColorData("E5E0E1", "Bon Jour"),
        ColorData("E5E5E5", "Mercury"),
        ColorData("E5F9F6", "Polar"),
        ColorData("E64E03", "Trinidad"),
        ColorData("E6BE8A", "Gold Sand"),
        ColorData("E6BEA5", "Cashmere"),
        ColorData("E6D7B9", "Double Spanish White"),
        ColorData("E6E4D4", "Satin Linen"),
        ColorData("E6F2EA", "Harp"),
        ColorData("E6F8F3", "Off Green"),
        ColorData("E6FFE9", "Hint of Green"),
        ColorData("E6FFFF", "Tranquil"),
        ColorData("E77200", "Mango Tango"),
        ColorData("E7730A", "Christine"),
        ColorData("E79F8C", "Tonys Pink"),
        ColorData("E79FC4", "Kobi"),
        ColorData("E7BCB4", "Rose Fog"),
        ColorData("E7BF05", "Corn"),
        ColorData("E7CD8C", "Putty"),
        ColorData("E7ECE6", "Gray Nurse"),
        ColorData("E7F8FF", "Lily White"),
        ColorData("E7FEFF", "Bubbles"),
        ColorData("E89928", "Fire Bush"),
        ColorData("E8B9B3", "Shilo"),
        ColorData("E8E0D5", "Pearl Bush"),
        ColorData("E8EBE0", "Green White"),
        ColorData("E8F1D4", "Chrome White"),
        ColorData("E8F2EB", "Gin"),
        ColorData("E8F5F2", "Aqua Squeeze"),
        ColorData("E96E00", "Clementine"),
        ColorData("E97451", "Burnt Sienna"),
        ColorData("E97C07", "Tahiti Gold"),
        ColorData("E9CECD", "Oyster Pink"),
        ColorData("E9D75A", "Confetti"),
        ColorData("E9E3E3", "Ebb"),
        ColorData("E9F8ED", "Ottoman"),
        ColorData("E9FFFD", "Clear Day"),
        ColorData("EA88A8", "Carissma"),
        ColorData("EAAE69", "Porsche"),
        ColorData("EAB33B", "Tulip Tree"),
        ColorData("EAC674", "Rob Roy"),
        ColorData("EADAB8", "Raffia"),
        ColorData("EAE8D4", "White Rock"),
        ColorData("EAF6EE", "Panache"),
        ColorData("EAF6FF", "Solitude"),
        ColorData("EAF9F5", "Aqua Spring"),
        ColorData("EAFFFE", "Dew"),
        ColorData("EB9373", "Apricot"),
        ColorData("EBC2AF", "Zinnwaldite"),
        ColorData("ECA927", "Fuel Yellow"),
        ColorData("ECC54E", "Ronchi"),
        ColorData("ECC7EE", "French Lilac"),
        ColorData("ECCDB9", "Just Right"),
        ColorData("ECE090", "Wild Rice"),
        ColorData("ECEBBD", "Fall Green"),
        ColorData("ECEBCE", "Aths Special"),
        ColorData("ECF245", "Starship"),
        ColorData("ED0A3F", "Red Ribbon"),
        ColorData("ED7A1C", "Tango"),
        ColorData("ED9121", "Carrot Orange"),
        ColorData("ED989E", "Sea Pink"),
        ColorData("EDB381", "Tacao"),
        ColorData("EDC9AF", "Desert Sand"),
        ColorData("EDCDAB", "Pancho"),
        ColorData("EDDCB1", "Chamois"),
        ColorData("EDEA99", "Primrose"),
        ColorData("EDF5DD", "Frost"),
        ColorData("EDF5F5", "Aqua Haze"),
        ColorData("EDF6FF", "Zumthor"),
        ColorData("EDF9F1", "Narvik"),
        ColorData("EDFC84", "Honeysuckle"),
        ColorData("EE82EE", "Lavender Magenta"),
        ColorData("EEC1BE", "Beauty Bush"),
        ColorData("EED794", "Chalky"),
        ColorData("EED9C4", "Almond"),
        ColorData("EEDC82", "Flax"),
        ColorData("EEDEDA", "Bizarre"),
        ColorData("EEE3AD", "Double Colonial White"),
        ColorData("EEEEE8", "Cararra"),
        ColorData("EEEF78", "Manz"),
        ColorData("EEF0C8", "Tahuna Sands"),
        ColorData("EEF0F3", "Athens Gray"),
        ColorData("EEF3C3", "Tusk"),
        ColorData("EEF4DE", "Loafer"),
        ColorData("EEF6F7", "Catskill White"),
        ColorData("EEFDFF", "Twilight Blue"),
        ColorData("EEFF9A", "Jonquil"),
        ColorData("EEFFE2", "Rice Flower"),
        ColorData("EF863F", "Jaffa"),
        ColorData("EFEFEF", "Gallery"),
        ColorData("EFF2F3", "Porcelain"),
        ColorData("F091A9", "Mauvelous"),
        ColorData("F0D52D", "Golden Dream"),
        ColorData("F0DB7D", "Golden Sand"),
        ColorData("F0DC82", "Buff"),
        ColorData("F0E2EC", "Prim"),
        ColorData("F0E68C", "Khaki"),
        ColorData("F0EEFD", "Selago"),
        ColorData("F0EEFF", "Titan White"),
        ColorData("F0F8FF", "Alice Blue"),
        ColorData("F0FCEA", "Feta"),
        ColorData("F18200", "Gold Drop"),
        ColorData("F19BAB", "Wewak"),
        ColorData("F1E788", "Sahara Sand"),
        ColorData("F1E9D2", "Parchment"),
        ColorData("F1E9FF", "Blue Chalk"),
        ColorData("F1EEC1", "Mint Julep"),
        ColorData("F1F1F1", "Seashell"),
        ColorData("F1F7F2", "Saltpan"),
        ColorData("F1FFAD", "Tidal"),
        ColorData("F1FFC8", "Chiffon"),
        ColorData("F2552A", "Flamingo"),
        ColorData("F28500", "Tangerine"),
        ColorData("F2C3B2", "Mandys Pink"),
        ColorData("F2F2F2", "Concrete"),
        ColorData("F2FAFA", "Black Squeeze"),
        ColorData("F34723", "Pomegranate"),
        ColorData("F3AD16", "Buttercup"),
        ColorData("F3D69D", "New Orleans"),
        ColorData("F3D9DF", "Vanilla Ice"),
        ColorData("F3E7BB", "Sidecar"),
        ColorData("F3E9E5", "Dawn Pink"),
        ColorData("F3EDCF", "Wheatfield"),
        ColorData("F3FB62", "Canary"),
        ColorData("F3FBD4", "Orinoco"),
        ColorData("F3FFD8", "Carla"),
        ColorData("F400A1", "Hollywood Cerise"),
        ColorData("F4A460", "Sandy brown"),
        ColorData("F4C430", "Saffron"),
        ColorData("F4D81C", "Ripe Lemon"),
        ColorData("F4EBD3", "Janna"),
        ColorData("F4F2EE", "Pampas"),
        ColorData("F4F4F4", "Wild Sand"),
        ColorData("F4F8FF", "Zircon"),
        ColorData("F57584", "Froly"),
        ColorData("F5C85C", "Cream Can"),
        ColorData("F5C999", "Manhattan"),
        ColorData("F5D5A0", "Maize"),
        ColorData("F5DEB3", "Wheat"),
        ColorData("F5E7A2", "Sandwisp"),
        ColorData("F5E7E2", "Pot Pourri"),
        ColorData("F5E9D3", "Albescent White"),
        ColorData("F5EDEF", "Soft Peach"),
        ColorData("F5F3E5", "Ecru White"),
        ColorData("F5F5DC", "Beige"),
        ColorData("F5FB3D", "Golden Fizz"),
        ColorData("F5FFBE", "Australian Mint"),
        ColorData("F64A8A", "French Rose"),
        ColorData("F653A6", "Brilliant Rose"),
        ColorData("F6A4C9", "Illusion"),
        ColorData("F6F0E6", "Merino"),
        ColorData("F6F7F7", "Black Haze"),
        ColorData("F6FFDC", "Spring Sun"),
        ColorData("F7468A", "Violet Red"),
        ColorData("F77703", "Chilean Fire"),
        ColorData("F77FBE", "Persian Pink"),
        ColorData("F7B668", "Rajah"),
        ColorData("F7C8DA", "Azalea"),
        ColorData("F7DBE6", "We Peep"),
        ColorData("F7F2E1", "Quarter Spanish White"),
        ColorData("F7F5FA", "Whisper"),
        ColorData("F7FAF7", "Snow Drift"),
        ColorData("F8B853", "Casablanca"),
        ColorData("F8C3DF", "Chantilly"),
        ColorData("F8D9E9", "Cherub"),
        ColorData("F8DB9D", "Marzipan"),
        ColorData("F8DD5C", "Energy Yellow"),
        ColorData("F8E4BF", "Givry"),
        ColorData("F8F0E8", "White Linen"),
        ColorData("F8F4FF", "Magnolia"),
        ColorData("F8F6F1", "Spring Wood"),
        ColorData("F8F7DC", "Coconut Cream"),
        ColorData("F8F7FC", "White Lilac"),
        ColorData("F8F8F7", "Desert Storm"),
        ColorData("F8F99C", "Texas"),
        ColorData("F8FACD", "Corn Field"),
        ColorData("F8FDD3", "Mimosa"),
        ColorData("F95A61", "Carnation"),
        ColorData("F9BF58", "Saffron Mango"),
        ColorData("F9E0ED", "Carousel Pink"),
        ColorData("F9E4BC", "Dairy Cream"),
        ColorData("F9E663", "Portica"),
        ColorData("F9EAF3", "Amour"),
        ColorData("F9F8E4", "Rum Swizzle"),
        ColorData("F9FF8B", "Dolly"),
        ColorData("F9FFF6", "Sugar Cane"),
        ColorData("FA7814", "Ecstasy"),
        ColorData("FA9D5A", "Tan Hide"),
        ColorData("FAD3A2", "Corvette"),
        ColorData("FADFAD", "Peach Yellow"),
        ColorData("FAE600", "Turbo"),
        ColorData("FAEAB9", "Astra"),
        ColorData("FAECCC", "Champagne"),
        ColorData("FAF0E6", "Linen"),
        ColorData("FAF3F0", "Fantasy"),
        ColorData("FAF7D6", "Citrine White"),
        ColorData("FAFAFA", "Alabaster"),
        ColorData("FAFDE4", "Hint of Yellow"),
        ColorData("FAFFA4", "Milan"),
        ColorData("FB607F", "Brink Pink"),
        ColorData("FB8989", "Geraldine"),
        ColorData("FBA0E3", "Lavender Rose"),
        ColorData("FBA129", "Sea Buckthorn"),
        ColorData("FBAC13", "Sun"),
        ColorData("FBAED2", "Lavender Pink"),
        ColorData("FBB2A3", "Rose Bud"),
        ColorData("FBBEDA", "Cupid"),
        ColorData("FBCCE7", "Classic Rose"),
        ColorData("FBCEB1", "Apricot Peach"),
        ColorData("FBE7B2", "Banana Mania"),
        ColorData("FBE870", "Marigold Yellow"),
        ColorData("FBE96C", "Festival"),
        ColorData("FBEA8C", "Sweet Corn"),
        ColorData("FBEC5D", "Candy Corn"),
        ColorData("FBF9F9", "Hint of Red"),
        ColorData("FBFFBA", "Shalimar"),
        ColorData("FC0FC0", "Shocking Pink"),
        ColorData("FC80A5", "Tickle Me Pink"),
        ColorData("FC9C1D", "Tree Poppy"),
        ColorData("FCC01E", "Lightning Yellow"),
        ColorData("FCD667", "Goldenrod"),
        ColorData("FCD917", "Candlelight"),
        ColorData("FCDA98", "Cherokee"),
        ColorData("FCF4D0", "Double Pearl Lusta"),
        ColorData("FCF4DC", "Pearl Lusta"),
        ColorData("FCF8F7", "Vista White"),
        ColorData("FCFBF3", "Bianca"),
        ColorData("FCFEDA", "Moon Glow"),
        ColorData("FCFFE7", "China Ivory"),
        ColorData("FCFFF9", "Ceramic"),
        ColorData("FD0E35", "Torch Red"),
        ColorData("FD5B78", "Wild Watermelon"),
        ColorData("FD7B33", "Crusta"),
        ColorData("FD7C07", "Sorbus"),
        ColorData("FD9FA2", "Sweet Pink"),
        ColorData("FDD5B1", "Light Apricot"),
        ColorData("FDD7E4", "Pig Pink"),
        ColorData("FDE1DC", "Cinderella"),
        ColorData("FDE295", "Golden Glow"),
        ColorData("FDE910", "Lemon"),
        ColorData("FDF5E6", "Old Lace"),
        ColorData("FDF6D3", "Half Colonial White"),
        ColorData("FDF7AD", "Drover"),
        ColorData("FDFEB8", "Pale Prim"),
        ColorData("FDFFD5", "Cumulus"),
        ColorData("FE28A2", "Persian Rose"),
        ColorData("FE4C40", "Sunset Orange"),
        ColorData("FE6F5E", "Bittersweet"),
        ColorData("FE9D04", "California"),
        ColorData("FEA904", "Yellow Sea"),
        ColorData("FEBAAD", "Melon"),
        ColorData("FED33C", "Bright Sun"),
        ColorData("FED85D", "Dandelion"),
        ColorData("FEDB8D", "Salomie"),
        ColorData("FEE5AC", "Cape Honey"),
        ColorData("FEEBF3", "Remy"),
        ColorData("FEEFCE", "Oasis"),
        ColorData("FEF0EC", "Bridesmaid"),
        ColorData("FEF2C7", "Beeswax"),
        ColorData("FEF3D8", "Bleach White"),
        ColorData("FEF4CC", "Pipi"),
        ColorData("FEF4DB", "Half Spanish White"),
        ColorData("FEF4F8", "Wisp Pink"),
        ColorData("FEF5F1", "Provincial Pink"),
        ColorData("FEF7DE", "Half Dutch White"),
        ColorData("FEF8E2", "Solitaire"),
        ColorData("FEF8FF", "White Pointer"),
        ColorData("FEF9E3", "Off Yellow"),
        ColorData("FEFCED", "Orange White"),
        ColorData("FF0000", "Red"),
        ColorData("FF007F", "Rose"),
        ColorData("FF00CC", "Purple Pizzazz"),
        ColorData("FF00FF", "Magenta / Fuchsia"),
        ColorData("FF2400", "Scarlet"),
        ColorData("FF3399", "Wild Strawberry"),
        ColorData("FF33CC", "Razzle Dazzle Rose"),
        ColorData("FF355E", "Radical Red"),
        ColorData("FF3F34", "Red Orange"),
        ColorData("FF4040", "Coral Red"),
        ColorData("FF4D00", "Vermilion"),
        ColorData("FF4F00", "International Orange"),
        ColorData("FF6037", "Outrageous Orange"),
        ColorData("FF6600", "Blaze Orange"),
        ColorData("FF66FF", "Pink Flamingo"),
        ColorData("FF681F", "Orange"),
        ColorData("FF69B4", "Hot Pink"),
        ColorData("FF6B53", "Persimmon"),
        ColorData("FF6FFF", "Blush Pink"),
        ColorData("FF7034", "Burning Orange"),
        ColorData("FF7518", "Pumpkin"),
        ColorData("FF7D07", "Flamenco"),
        ColorData("FF7F00", "Flush Orange"),
        ColorData("FF7F50", "Coral"),
        ColorData("FF8C69", "Salmon"),
        ColorData("FF9000", "Pizazz"),
        ColorData("FF910F", "West Side"),
        ColorData("FF91A4", "Pink Salmon"),
        ColorData("FF9933", "Neon Carrot"),
        ColorData("FF9966", "Atomic Tangerine"),
        ColorData("FF9980", "Vivid Tangerine"),
        ColorData("FF9E2C", "Sunshade"),
        ColorData("FFA000", "Orange Peel"),
        ColorData("FFA194", "Mona Lisa"),
        ColorData("FFA500", "Web Orange"),
        ColorData("FFA6C9", "Carnation Pink"),
        ColorData("FFAB81", "Hit Pink"),
        ColorData("FFAE42", "Yellow Orange"),
        ColorData("FFB0AC", "Cornflower Lilac"),
        ColorData("FFB1B3", "Sundown"),
        ColorData("FFB31F", "My Sin"),
        ColorData("FFB555", "Texas Rose"),
        ColorData("FFB7D5", "Cotton Candy"),
        ColorData("FFB97B", "Macaroni and Cheese"),
        ColorData("FFBA00", "Selective Yellow"),
        ColorData("FFBD5F", "Koromiko"),
        ColorData("FFBF00", "Amber"),
        ColorData("FFC0A8", "Wax Flower"),
        ColorData("FFC0CB", "Pink"),
        ColorData("FFC3C0", "Your Pink"),
        ColorData("FFC901", "Supernova"),
        ColorData("FFCBA4", "Flesh"),
        ColorData("FFCC33", "Sunglow"),
        ColorData("FFCC5C", "Golden Tainoi"),
        ColorData("FFCC99", "Peach Orange"),
        ColorData("FFCD8C", "Chardonnay"),
        ColorData("FFD1DC", "Pastel Pink"),
        ColorData("FFD2B7", "Romantic"),
        ColorData("FFD38C", "Grandis"),
        ColorData("FFD700", "Gold"),
        ColorData("FFD800", "School bus Yellow"),
        ColorData("FFD8D9", "Cosmos"),
        ColorData("FFDB58", "Mustard"),
        ColorData("FFDCD6", "Peach Schnapps"),
        ColorData("FFDDAF", "Caramel"),
        ColorData("FFDDCD", "Tuft Bush"),
        ColorData("FFDDCF", "Watusi"),
        ColorData("FFDDF4", "Pink Lace"),
        ColorData("FFDEAD", "Navajo White"),
        ColorData("FFDEB3", "Frangipani"),
        ColorData("FFE1DF", "Pippin"),
        ColorData("FFE1F2", "Pale Rose"),
        ColorData("FFE2C5", "Negroni"),
        ColorData("FFE5A0", "Cream Brulee"),
        ColorData("FFE5B4", "Peach"),
        ColorData("FFE6C7", "Tequila"),
        ColorData("FFE772", "Kournikova"),
        ColorData("FFEAC8", "Sandy Beach"),
        ColorData("FFEAD4", "Karry"),
        ColorData("FFEC13", "Broom"),
        ColorData("FFEDBC", "Colonial White"),
        ColorData("FFEED8", "Derby"),
        ColorData("FFEFA1", "Vis Vis"),
        ColorData("FFEFC1", "Egg White"),
        ColorData("FFEFD5", "Papaya Whip"),
        ColorData("FFEFEC", "Fair Pink"),
        ColorData("FFF0DB", "Peach Cream"),
        ColorData("FFF0F5", "Lavender blush"),
        ColorData("FFF14F", "Gorse"),
        ColorData("FFF1B5", "Buttermilk"),
        ColorData("FFF1D8", "Pink Lady"),
        ColorData("FFF1EE", "Forget Me Not"),
        ColorData("FFF1F9", "Tutu"),
        ColorData("FFF39D", "Picasso"),
        ColorData("FFF3F1", "Chardon"),
        ColorData("FFF46E", "Paris Daisy"),
        ColorData("FFF4CE", "Barley White"),
        ColorData("FFF4DD", "Egg Sour"),
        ColorData("FFF4E0", "Sazerac"),
        ColorData("FFF4E8", "Serenade"),
        ColorData("FFF4F3", "Chablis"),
        ColorData("FFF5EE", "Seashell Peach"),
        ColorData("FFF5F3", "Sauvignon"),
        ColorData("FFF6D4", "Milk Punch"),
        ColorData("FFF6DF", "Varden"),
        ColorData("FFF6F5", "Rose White"),
        ColorData("FFF8D1", "Baja White"),
        ColorData("FFF9E2", "Gin Fizz"),
        ColorData("FFF9E6", "Early Dawn"),
        ColorData("FFFACD", "Lemon Chiffon"),
        ColorData("FFFAF4", "Bridal Heath"),
        ColorData("FFFBDC", "Scotch Mist"),
        ColorData("FFFBF9", "Soapstone"),
        ColorData("FFFC99", "Witch Haze"),
        ColorData("FFFCEA", "Buttery White"),
        ColorData("FFFCEE", "Island Spice"),
        ColorData("FFFDD0", "Cream"),
        ColorData("FFFDE6", "Chilean Heath"),
        ColorData("FFFDE8", "Travertine"),
        ColorData("FFFDF3", "Orchid White"),
        ColorData("FFFDF4", "Quarter Pearl Lusta"),
        ColorData("FFFEE1", "Half and Half"),
        ColorData("FFFEEC", "Apricot White"),
        ColorData("FFFEF0", "Rice Cake"),
        ColorData("FFFEF6", "Black White"),
        ColorData("FFFEFD", "Romance"),
        ColorData("FFFF00", "Yellow"),
        ColorData("FFFF66", "Laser Lemon"),
        ColorData("FFFF99", "Pale Canary"),
        ColorData("FFFFB4", "Portafino"),
        ColorData("FFFFF0", "Ivory"),
        ColorData("FFFFFF", "White"),
    ]
}
