import SwiftUI

extension ColorList {
    static let Colors1 = [
        ColorData("6D6C6C", "Dove Gray"),
        ColorData("6D9292", "Juniper"),
        ColorData("6D92A1", "Gothic"),
        ColorData("6E0902", "Red Oxide"),
        ColorData("6E1D14", "Moccaccino"),
        ColorData("6E4826", "Pickled Bean"),
        ColorData("6E4B26", "Dallas"),
        ColorData("6E6D57", "Kokoda"),
        ColorData("6E7783", "Pale Sky"),
        ColorData("6F440C", "Cafe Royale"),
        ColorData("6F6A61", "Flint"),
        ColorData("6F8E63", "Highland"),
        ColorData("6F9D02", "Limeade"),
        ColorData("6FD0C5", "Downy"),
        ColorData("701C1C", "Persian Plum"),
        ColorData("704214", "Sepia"),
        ColorData("704A07", "Antique Bronze"),
        ColorData("704F50", "Ferra"),
        ColorData("706555", "Coffee"),
        ColorData("708090", "Slate Gray"),
        ColorData("711A00", "Cedar Wood Finish"),
        ColorData("71291D", "Metallic Copper"),
        ColorData("714693", "Affair"),
        ColorData("714AB2", "Studio"),
        ColorData("715D47", "Tobacco Brown"),
        ColorData("716338", "Yellow Metal"),
        ColorData("716B56", "Peat"),
        ColorData("716E10", "Olivetone"),
        ColorData("717486", "Storm Gray"),
        ColorData("718080", "Sirocco"),
        ColorData("71D9E2", "Aquamarine Blue"),
        ColorData("72010F", "Venetian Red"),
        ColorData("724A2F", "Old Copper"),
        ColorData("726D4E", "Go Ben"),
        ColorData("727B89", "Raven"),
        ColorData("731E8F", "Seance"),
        ColorData("734A12", "Raw Umber"),
        ColorData("736C9F", "Kimberly"),
        ColorData("736D58", "Crocodile"),
        ColorData("737829", "Crete"),
        ColorData("738678", "Xanadu"),
        ColorData("74640D", "Spicy Mustard"),
        ColorData("747D63", "Limed Ash"),
        ColorData("747D83", "Rolling Stone"),
        ColorData("748881", "Blue Smoke"),
        ColorData("749378", "Laurel"),
        ColorData("74C365", "Mantis"),
        ColorData("755A57", "Russett"),
        ColorData("7563A8", "Deluge"),
        ColorData("76395D", "Cosmic"),
        ColorData("7666C6", "Blue Marguerite"),
        ColorData("76BD17", "Lima"),
        ColorData("76D7EA", "Sky Blue"),
        ColorData("770F05", "Dark Burgundy"),
        ColorData("771F1F", "Crown of Thorns"),
        ColorData("773F1A", "Walnut"),
        ColorData("776F61", "Pablo"),
        ColorData("778120", "Pacifika"),
        ColorData("779E86", "Oxley"),
        ColorData("77DD77", "Pastel Green"),
        ColorData("780109", "Japanese Maple"),
        ColorData("782D19", "Mocha"),
        ColorData("782F16", "Peanut"),
        ColorData("78866B", "Camouflage Green"),
        ColorData("788A25", "Wasabi"),
        ColorData("788BBA", "Ship Cove"),
        ColorData("78A39C", "Sea Nymph"),
        ColorData("795D4C", "Roman Coffee"),
        ColorData("796878", "Old Lavender"),
        ColorData("796989", "Rum"),
        ColorData("796A78", "Fedora"),
        ColorData("796D62", "Sandstone"),
        ColorData("79DEEC", "Spray"),
        ColorData("7A013A", "Siren"),
        ColorData("7A58C1", "Fuchsia Blue"),
        ColorData("7A7A7A", "Boulder"),
        ColorData("7A89B8", "Wild Blue Yonder"),
        ColorData("7AC488", "De York"),
        ColorData("7B3801", "Red Beech"),
        ColorData("7B3F00", "Cinnamon"),
        ColorData("7B6608", "Yukon Gold"),
        ColorData("7B7874", "Tapa"),
        ColorData("7B7C94", "Waterloo "),
        ColorData("7B8265", "Flax Smoke"),
        ColorData("7B9F80", "Amulet"),
        ColorData("7BA05B", "Asparagus"),
        ColorData("7C1C05", "Kenyan Copper"),
        ColorData("7C7631", "Pesto"),
        ColorData("7C778A", "Topaz"),
        ColorData("7C7B7A", "Concord"),
        ColorData("7C7B82", "Jumbo"),
        ColorData("7C881A", "Trendy Green"),
        ColorData("7CA1A6", "Gumbo"),
        ColorData("7CB0A1", "Acapulco"),
        ColorData("7CB7BB", "Neptune"),
        ColorData("7D2C14", "Pueblo"),
        ColorData("7DA98D", "Bay Leaf"),
        ColorData("7DC8F7", "Malibu"),
        ColorData("7DD8C6", "Bermuda"),
        ColorData("7E3A15", "Copper Canyon"),
        ColorData("7F1734", "Claret"),
        ColorData("7F3A02", "Peru Tan"),
        ColorData("7F626D", "Falcon"),
        ColorData("7F7589", "Mobster"),
        ColorData("7F76D3", "Moody Blue"),
        ColorData("7FFF00", "Chartreuse"),
        ColorData("7FFFD4", "Aquamarine"),
        ColorData("800000", "Maroon"),
        ColorData("800B47", "Rose Bud Cherry"),
        ColorData("801818", "Falu Red"),
        ColorData("80341F", "Red Robin"),
        ColorData("803790", "Vivid Violet"),
        ColorData("80461B", "Russet"),
        ColorData("807E79", "Friar Gray"),
        ColorData("808000", "Olive"),
        ColorData("808080", "Gray"),
        ColorData("80B3AE", "Gulf Stream"),
        ColorData("80B3C4", "Glacier"),
        ColorData("80CCEA", "Seagull"),
        ColorData("81422C", "Nutmeg"),
        ColorData("816E71", "Spicy Pink"),
        ColorData("817377", "Empress"),
        ColorData("819885", "Spanish Green"),
        ColorData("826F65", "Sand Dune"),
        ColorData("828685", "Gunsmoke"),
        ColorData("828F72", "Battleship Gray"),
        ColorData("831923", "Merlot"),
        ColorData("837050", "Shadow"),
        ColorData("83AA5D", "Chelsea Cucumber"),
        ColorData("83D0C6", "Monte Carlo"),
        ColorData("843179", "Plum"),
        ColorData("84A0A0", "Granny Smith"),
        ColorData("8581D9", "Chetwode Blue"),
        ColorData("858470", "Bandicoot"),
        ColorData("859FAF", "Bali Hai"),
        ColorData("85C4CC", "Half Baked"),
        ColorData("860111", "Red Devil"),
        ColorData("863C3C", "Lotus"),
        ColorData("86483C", "Ironstone"),
        ColorData("864D1E", "Bull Shot"),
        ColorData("86560A", "Rusty Nail"),
        ColorData("868974", "Bitter"),
        ColorData("86949F", "Regent Gray"),
        ColorData("871550", "Disco"),
        ColorData("87756E", "Americano"),
        ColorData("877C7B", "Hurricane"),
        ColorData("878D91", "Oslo Gray"),
        ColorData("87AB39", "Sushi"),
        ColorData("885342", "Spicy Mix"),
        ColorData("886221", "Kumera"),
        ColorData("888387", "Suva Gray"),
        ColorData("888D65", "Avocado"),
        ColorData("893456", "Camelot"),
        ColorData("893843", "Solid Pink"),
        ColorData("894367", "Cannon Pink"),
        ColorData("897D6D", "Makara"),
        ColorData("8A3324", "Burnt Umber"),
        ColorData("8A73D6", "True V"),
        ColorData("8A8360", "Clay Creek"),
        ColorData("8A8389", "Monsoon"),
        ColorData("8A8F8A", "Stack"),
        ColorData("8AB9F1", "Jordy Blue"),
        ColorData("8B00FF", "Electric Violet"),
        ColorData("8B0723", "Monarch"),
        ColorData("8B6B0B", "Corn Harvest"),
        ColorData("8B8470", "Olive Haze"),
        ColorData("8B847E", "Schooner"),
        ColorData("8B8680", "Natural Gray"),
        ColorData("8B9C90", "Mantle"),
        ColorData("8B9FEE", "Portage"),
        ColorData("8BA690", "Envy"),
        ColorData("8BA9A5", "Cascade"),
        ColorData("8BE6D8", "Riptide"),
        ColorData("8C055E", "Cardinal Pink"),
        ColorData("8C472F", "Mule Fawn"),
        ColorData("8C5738", "Potters Clay"),
        ColorData("8C6495", "Trendy Pink"),
        ColorData("8D0226", "Paprika"),
        ColorData("8D3D38", "Sanguine Brown"),
        ColorData("8D3F3F", "Tosca"),
        ColorData("8D7662", "Cement"),
        ColorData("8D8974", "Granite Green"),
        ColorData("8D90A1", "Manatee"),
        ColorData("8DA8CC", "Polo Blue"),
        ColorData("8E0000", "Red Berry"),
        ColorData("8E4D1E", "Rope"),
        ColorData("8E6F70", "Opium"),
        ColorData("8E775E", "Domino"),
        ColorData("8E8190", "Mamba"),
        ColorData("8EABC1", "Nepal"),
        ColorData("8F021C", "Pohutukawa"),
        ColorData("8F3E33", "El Salva"),
        ColorData("8F4B0E", "Korma"),
        ColorData("8F8176", "Squirrel"),
        ColorData("8FD6B4", "Vista Blue"),
        ColorData("900020", "Burgundy"),
        ColorData("901E1E", "Old Brick"),
        ColorData("907874", "Hemp"),
        ColorData("907B71", "Almond Frost"),
        ColorData("908D39", "Sycamore"),
        ColorData("92000A", "Sangria"),
        ColorData("924321", "Cumin"),
        ColorData("926F5B", "Beaver"),
        ColorData("928573", "Stonewall"),
        ColorData("928590", "Venus"),
        ColorData("9370DB", "Medium Purple"),
        ColorData("93CCEA", "Cornflower"),
        ColorData("93DFB8", "Algae Green"),
        ColorData("944747", "Copper Rust"),
        ColorData("948771", "Arrowtown"),
        ColorData("950015", "Scarlett"),
        ColorData("956387", "Strikemaster"),
        ColorData("959396", "Mountain Mist"),
        ColorData("960018", "Carmine"),
        ColorData("964B00", "Brown"),
        ColorData("967059", "Leather"),
        ColorData("9678B6", "Purple Mountain's Majesty"),
        ColorData("967BB6", "Lavender Purple"),
        ColorData("96A8A1", "Pewter"),
        ColorData("96BBAB", "Summer Green"),
        ColorData("97605D", "Au Chico"),
        ColorData("9771B5", "Wisteria"),
        ColorData("97CD2D", "Atlantis"),
        ColorData("983D61", "Vin Rouge"),
        ColorData("9874D3", "Lilac Bush"),
        ColorData("98777B", "Bazaar"),
        ColorData("98811B", "Hacienda"),
        ColorData("988D77", "Pale Oyster"),
        ColorData("98FF98", "Mint Green"),
        ColorData("990066", "Fresh Eggplant"),
        ColorData("991199", "Violet Eggplant"),
        ColorData("991613", "Tamarillo"),
        ColorData("991B07", "Totem Pole"),
        ColorData("996666", "Copper Rose"),
        ColorData("9966CC", "Amethyst"),
        ColorData("997A8D", "Mountbatten Pink"),
        ColorData("9999CC", "Blue Bell"),
        ColorData("9A3820", "Prairie Sand"),
        ColorData("9A6E61", "Toast"),
        ColorData("9A9577", "Gurkha"),
        ColorData("9AB973", "Olivine"),
        ColorData("9AC2B8", "Shadow Green"),
        ColorData("9B4703", "Oregon"),
        ColorData("9B9E8F", "Lemon Grass"),
        ColorData("9C3336", "Stiletto"),
        ColorData("9D5616", "Hawaiian Tan"),
        ColorData("9DACB7", "Gull Gray"),
        ColorData("9DC209", "Pistachio"),
        ColorData("9DE093", "Granny Smith Apple"),
        ColorData("9DE5FF", "Anakiwa"),
        ColorData("9E5302", "Chelsea Gem"),
        ColorData("9E5B40", "Sepia Skin"),
        ColorData("9EA587", "Sage"),
        ColorData("9EA91F", "Citron"),
        ColorData("9EB1CD", "Rock Blue"),
        ColorData("9EDEE0", "Morning Glory"),
        ColorData("9F381D", "Cognac"),
        ColorData("9F821C", "Reef Gold"),
        ColorData("9F9F9C", "Star Dust"),
        ColorData("9FA0B1", "Santas Gray"),
        ColorData("9FD7D3", "Sinbad"),
        ColorData("9FDD8C", "Feijoa"),
        ColorData("A02712", "Tabasco"),
        ColorData("A1750D", "Buttered Rum"),
        ColorData("A1ADB5", "Hit Gray"),
        ColorData("A1C50A", "Citrus"),
        ColorData("A1DAD7", "Aqua Island"),
        ColorData("A1E9DE", "Water Leaf"),
        ColorData("A2006D", "Flirt"),
        ColorData("A23B6C", "Rouge"),
        ColorData("A26645", "Cape Palliser"),
        ColorData("A2AAB3", "Gray Chateau"),
        ColorData("A2AEAB", "Edward"),
        ColorData("A3807B", "Pharlap"),
        ColorData("A397B4", "Amethyst Smoke"),
        ColorData("A3E3ED", "Blizzard Blue"),
        ColorData("A4A49D", "Delta"),
        ColorData("A4A6D3", "Wistful"),
        ColorData("A4AF6E", "Green Smoke"),
        ColorData("A50B5E", "Jazzberry Jam"),
        ColorData("A59B91", "Zorba"),
        ColorData("A5CB0C", "Bahia"),
        ColorData("A62F20", "Roof Terracotta"),
        ColorData("A65529", "Paarl"),
        ColorData("A68B5B", "Barley Corn"),
        ColorData("A69279", "Donkey Brown"),
        ColorData("A6A29A", "Dawn"),
        ColorData("A72525", "Mexican Red"),
        ColorData("A7882C", "Luxor Gold"),
        ColorData("A85307", "Rich Gold"),
        ColorData("A86515", "Reno Sand"),
        ColorData("A86B6B", "Coral Tree"),
        ColorData("A8989B", "Dusty Gray"),
        ColorData("A899E6", "Dull Lavender"),
        ColorData("A8A589", "Tallow"),
        ColorData("A8AE9C", "Bud"),
        ColorData("A8AF8E", "Locust"),
        ColorData("A8BD9F", "Norway"),
        ColorData("A8E3BD", "Chinook"),
        ColorData("A9A491", "Gray Olive"),
        ColorData("A9ACB6", "Aluminium"),
        ColorData("A9B2C3", "Cadet Blue"),
        ColorData("A9B497", "Schist"),
        ColorData("A9BDBF", "Tower Gray"),
        ColorData("A9BEF2", "Perano"),
        ColorData("A9C6C2", "Opal"),
        ColorData("AA375A", "Night Shadz"),
        ColorData("AA4203", "Fire"),
        ColorData("AA8B5B", "Muesli"),
        ColorData("AA8D6F", "Sandal"),
        ColorData("AAA5A9", "Shady Lady"),
        ColorData("AAA9CD", "Logan"),
        ColorData("AAABB7", "Spun Pearl"),
        ColorData("AAD6E6", "Regent St Blue"),
        ColorData("AAF0D1", "Magic Mint"),
        ColorData("AB0563", "Lipstick"),
        ColorData("AB3472", "Royal Heath"),
        ColorData("AB917A", "Sandrift"),
        ColorData("ABA0D9", "Cold Purple"),
        ColorData("ABA196", "Bronco"),
        ColorData("AC8A56", "Limed Oak"),
        ColorData("AC91CE", "East Side"),
        ColorData("AC9E22", "Lemon Ginger"),
        ColorData("ACA494", "Napa"),
        ColorData("ACA586", "Hillary"),
        ColorData("ACA59F", "Cloudy"),
        ColorData("ACACAC", "Silver Chalice"),
        ColorData("ACB78E", "Swamp Green"),
        ColorData("ACCBB1", "Spring Rain"),
        ColorData("ACDD4D", "Conifer"),
        ColorData("ACE1AF", "Celadon"),
        ColorData("AD781B", "Mandalay"),
        ColorData("ADBED1", "Casper"),
        ColorData("ADDFAD", "Moss Green"),
        ColorData("ADE6C4", "Padua"),
        ColorData("ADFF2F", "Green Yellow"),
        ColorData("AE4560", "Hippie Pink"),
        ColorData("AE6020", "Desert"),
        ColorData("AE809E", "Bouquet"),
        ColorData("AF4035", "Medium Carmine"),
        ColorData("AF4D43", "Apple Blossom"),
        ColorData("AF593E", "Brown Rust"),
        ColorData("AF8751", "Driftwood"),
        ColorData("AF8F2C", "Alpine"),
        ColorData("AF9F1C", "Lucky"),
        ColorData("AFA09E", "Martini"),
        ColorData("AFB1B8", "Bombay"),
        ColorData("AFBDD9", "Pigeon Post"),
        ColorData("B04C6A", "Cadillac"),
        ColorData("B05D54", "Matrix"),
        ColorData("B05E81", "Tapestry"),
        ColorData("B06608", "Mai Tai"),
        ColorData("B09A95", "Del Rio"),
        ColorData("B0E0E6", "Powder Blue"),
        ColorData("B0E313", "Inch Worm"),
        ColorData("B10000", "Bright Red"),
        ColorData("B14A0B", "Vesuvius"),
        ColorData("B1610B", "Pumpkin Skin"),
        ColorData("B16D52", "Santa Fe"),
        ColorData("B19461", "Teak"),
        ColorData("B1E2C1", "Fringy Flower"),
        ColorData("B1F4E7", "Ice Cold"),
        ColorData("B20931", "Shiraz"),
        ColorData("B2A1EA", "Biloba Flower"),
        ColorData("B32D29", "Tall Poppy"),
        ColorData("B35213", "Fiery Orange"),
        ColorData("B38007", "Hot Toddy"),
        ColorData("B3AF95", "Taupe Gray"),
        ColorData("B3C110", "La Rioja"),
        ColorData("B43332", "Well Read"),
        ColorData("B44668", "Blush"),
        ColorData("B4CFD3", "Jungle Mist"),
        ColorData("B57281", "Turkish Rose"),
        ColorData("B57EDC", "Lavender"),
        ColorData("B5A27F", "Mongoose"),
        ColorData("B5B35C", "Olive Green"),
        ColorData("B5D2CE", "Jet Stream"),
        ColorData("B5ECDF", "Cruise"),
        ColorData("B6316C", "Hibiscus"),
        ColorData("B69D98", "Thatch"),
        ColorData("B6B095", "Heathered Gray"),
        ColorData("B6BAA4", "Eagle"),
        ColorData("B6D1EA", "Spindle"),
        ColorData("B6D3BF", "Gum Leaf"),
        ColorData("B7410E", "Rust"),
        ColorData("B78E5C", "Muddy Waters"),
        ColorData("B7A214", "Sahara"),
        ColorData("B7A458", "Husk"),
        ColorData("B7B1B1", "Nobel"),
        ColorData("B7C3D0", "Heather"),
        ColorData("B7F0BE", "Madang"),
        ColorData("B81104", "Milano Red"),
        ColorData("B87333", "Copper"),
        ColorData("B8B56A", "Gimblet"),
        ColorData("B8C1B1", "Green Spring"),
        ColorData("B8C25D", "Celery"),
        ColorData("B8E0F9", "Sail"),
        ColorData("B94E48", "Chestnut"),
        ColorData("B95140", "Crail"),
        ColorData("B98D28", "Marigold"),
        ColorData("B9C46A", "Wild Willow"),
        ColorData("B9C8AC", "Rainee"),
        ColorData("BA0101", "Guardsman Red"),
        ColorData("BA450C", "Rock Spray"),
        ColorData("BA6F1E", "Bourbon"),
        ColorData("BA7F03", "Pirate Gold"),
        ColorData("BAB1A2", "Nomad"),
        ColorData("BAC7C9", "Submarine"),
        ColorData("BAEEF9", "Charlotte"),
        ColorData("BB3385", "Medium Red Violet"),
        ColorData("BB8983", "Brandy Rose"),
        ColorData("BBD009", "Rio Grande"),
        ColorData("BBD7C1", "Surf"),
        ColorData("BCC9C2", "Powder Ash"),
        ColorData("BD5E2E", "Tuscany"),
        ColorData("BD978E", "Quicksand"),
        ColorData("BDB1A8", "Silk"),
        ColorData("BDB2A1", "Malta"),
        ColorData("BDB3C7", "Chatelle"),
        ColorData("BDBBD7", "Lavender Gray"),
        ColorData("BDBDC6", "French Gray"),
        ColorData("BDC8B3", "Clay Ash"),
        ColorData("BDC9CE", "Loblolly"),
        ColorData("BDEDFD", "French Pass"),
        ColorData("BEA6C3", "London Hue"),
        ColorData("BEB5B7", "Pink Swan"),
        ColorData("BEDE0D", "Fuego"),
        ColorData("BF5500", "Rose of Sharon"),
        ColorData("BFB8B0", "Tide"),
        ColorData("BFBED8", "Blue Haze"),
        ColorData("BFC1C2", "Silver Sand"),
        ColorData("BFC921", "Key Lime Pie"),
        ColorData("BFDBE2", "Ziggurat"),
        ColorData("BFFF00", "Lime"),
        ColorData("C02B18", "Thunderbird"),
        ColorData("C04737", "Mojo"),
        ColorData("C08081", "Old Rose"),
        ColorData("C0C0C0", "Silver"),
        ColorData("C0D3B9", "Pale Leaf"),
        ColorData("C0D8B6", "Pixie Green"),
        ColorData("C1440E", "Tia Maria"),
        ColorData("C154C1", "Fuchsia Pink"),
        ColorData("C1A004", "Buddha Gold"),
        ColorData("C1B7A4", "Bison Hide"),
        ColorData("C1BAB0", "Tea"),
        ColorData("C1BECD", "Gray Suit"),
        ColorData("C1D7B0", "Sprout"),
        ColorData("C1F07C", "Sulu"),
        ColorData("C26B03", "Indochine"),
        ColorData("C2955D", "Twine"),
        ColorData("C2BDB6", "Cotton Seed"),
        ColorData("C2CAC4", "Pumice"),
        ColorData("C2E8E5", "Jagged Ice"),
        ColorData("C32148", "Maroon Flush"),
        ColorData("C3B091", "Indian Khaki"),
        ColorData("C3BFC1", "Pale Slate"),
        ColorData("C3C3BD", "Gray Nickel"),
        ColorData("C3CDE6", "Periwinkle Gray"),
        ColorData("C3D1D1", "Tiara"),
        ColorData("C3DDF9", "Tropical Blue"),
        ColorData("C41E3A", "Cardinal"),
        ColorData("C45655", "Fuzzy Wuzzy Brown"),
        ColorData("C45719", "Orange Roughy"),
        ColorData("C4C4BC", "Mist Gray"),
        ColorData("C4D0B0", "Coriander"),
        ColorData("C4F4EB", "Mint Tulip"),
        ColorData("C54B8C", "Mulberry"),
        ColorData("C59922", "Nugget"),
        ColorData("C5994B", "Tussock"),
        ColorData("C5DBCA", "Sea Mist"),
        ColorData("C5E17A", "Yellow Green"),
        ColorData("C62D42", "Brick Red"),
        ColorData("C6726B", "Contessa"),
        ColorData("C69191", "Oriental Pink"),
        ColorData("C6A84B", "Roti"),
        ColorData("C6C3B5", "Ash"),
        ColorData("C6C8BD", "Kangaroo"),
        ColorData("C6E610", "Las Palmas"),
        ColorData("C7031E", "Monza"),
        ColorData("C71585", "Red Violet"),
        ColorData("C7BCA2", "Coral Reef"),
        ColorData("C7C1FF", "Melrose"),
        ColorData("C7C4BF", "Cloud"),
        ColorData("C7C9D5", "Ghost"),
        ColorData("C7CD90", "Pine Glade"),
        ColorData("C7DDE5", "Botticelli"),
        ColorData("C88A65", "Antique Brass"),
        ColorData("C8A2C8", "Lilac"),
        ColorData("C8A528", "Hokey Pokey"),
        ColorData("C8AABF", "Lily"),
        ColorData("C8B568", "Laser"),
        ColorData("C8E3D7", "Edgewater"),
        ColorData("C96323", "Piper"),
        ColorData("C99415", "Pizza"),
        ColorData("C9A0DC", "Light Wisteria"),
        ColorData("C9B29B", "Rodeo Dust"),
        ColorData("C9B35B", "Sundance"),
        ColorData("C9B93B", "Earls Green"),
        ColorData("C9C0BB", "Silver Rust"),
        ColorData("C9D9D2", "Conch"),
    ]
}
